const Task = require('../models/Task');
const Project = require('../models/Project');

const mockAIResponse = async (type, input) => {
  await new Promise(r => setTimeout(r, 800));
  const responses = {
    breakdown: {
      subtasks: [
        { title: 'Set up project structure and dependencies', priority: 'high' },
        { title: 'Create database schema and models', priority: 'high' },
        { title: 'Build API endpoints', priority: 'high' },
        { title: 'Implement authentication', priority: 'high' },
        { title: 'Create frontend components', priority: 'medium' },
        { title: 'Add form validation and error handling', priority: 'medium' },
        { title: 'Write unit tests', priority: 'medium' },
        { title: 'Deploy and configure environment', priority: 'low' },
      ],
      estimatedHours: 24,
      complexity: 'medium',
      suggestions: ['Consider using existing libraries', 'Break into smaller sprints', 'Prioritize MVP features first'],
    },
    standup: {
      report: `**Yesterday:** Worked on feature implementation and code review.\n**Today:** Continue development and resolve blockers.\n**Blockers:** None currently identified.\n\n*Generated by DevCollab AI*`,
    },
    summary: {
      summary: `This project is progressing well. The team has completed core functionality and is now focused on polish and testing. Key areas of focus include performance optimization and user experience improvements.`,
      healthScore: 78,
      risks: ['Deadline approaching', 'Test coverage needs improvement'],
      recommendations: ['Increase testing', 'Schedule code review sessions', 'Update documentation'],
    },
    codeReview: {
      issues: [
        { type: 'bug', severity: 'high', line: 12, message: 'Potential null pointer exception', suggestion: 'Add null check before accessing property' },
        { type: 'security', severity: 'medium', line: 24, message: 'Input not sanitized', suggestion: 'Use a validation library to sanitize user input' },
        { type: 'performance', severity: 'low', line: 36, message: 'Inefficient loop', suggestion: 'Consider using Array.reduce() for better performance' },
        { type: 'style', severity: 'info', line: 5, message: 'Missing JSDoc comment', suggestion: 'Add documentation for this function' },
      ],
      score: 72,
      summary: 'The code is generally well-structured but has some areas that need attention, particularly around input validation and error handling.',
    },
    blockers: {
      blockers: [
        { task: 'API Integration', issue: 'External API rate limiting', impact: 'high', suggestion: 'Implement request queuing' },
        { task: 'Performance', issue: 'Database queries are slow', impact: 'medium', suggestion: 'Add database indexes' },
      ],
      overallRisk: 'medium',
    },
  };
  return responses[type] || { message: 'AI response generated', data: {} };
};

exports.generateTaskBreakdown = async (req, res, next) => {
  try {
    const { taskTitle, description, projectId } = req.body;
    if (!taskTitle) return res.status(400).json({ success: false, message: 'Task title required' });
    const result = await mockAIResponse('breakdown', { taskTitle, description });
    res.json({ success: true, ...result });
  } catch (error) {
    next(error);
  }
};

exports.generateStandup = async (req, res, next) => {
  try {
    const { projectId } = req.body;
    const recentTasks = await Task.find({
      project: projectId,
      assignee: req.user._id,
      updatedAt: { $gte: new Date(Date.now() - 24 * 60 * 60 * 1000) },
    }).populate('assignee', 'name');
    const result = await mockAIResponse('standup', { tasks: recentTasks });
    res.json({ success: true, ...result, taskCount: recentTasks.length });
  } catch (error) {
    next(error);
  }
};

exports.generateProjectSummary = async (req, res, next) => {
  try {
    const { projectId } = req.params;
    const project = await Project.findById(projectId);
    if (!project) return res.status(404).json({ success: false, message: 'Project not found' });
    const tasks = await Task.find({ project: projectId });
    const result = await mockAIResponse('summary', { project, tasks });
    res.json({ success: true, project: project.name, ...result });
  } catch (error) {
    next(error);
  }
};

exports.reviewCode = async (req, res, next) => {
  try {
    const { code, language } = req.body;
    if (!code) return res.status(400).json({ success: false, message: 'Code is required' });
    const result = await mockAIResponse('codeReview', { code, language });
    res.json({ success: true, language: language || 'unknown', ...result });
  } catch (error) {
    next(error);
  }
};

exports.detectBlockers = async (req, res, next) => {
  try {
    const { projectId } = req.params;
    const overdueTasks = await Task.find({
      project: projectId,
      status: { $ne: 'done' },
      dueDate: { $lt: new Date() },
    }).populate('assignee', 'name');
    const result = await mockAIResponse('blockers', { overdueTasks });
    res.json({ success: true, overdueTasks: overdueTasks.length, ...result });
  } catch (error) {
    next(error);
  }
};

exports.chat = async (req, res, next) => {
  try {
    const { message } = req.body;
    await new Promise(r => setTimeout(r, 600));
    const responses = [
      "I've analyzed your project and found some optimization opportunities. Consider breaking down larger tasks into smaller, more manageable units.",
      "Based on the current progress, the project is on track. I recommend focusing on the critical path items first.",
      "I detected some potential blockers in your workflow. Let me suggest some solutions to keep the team productive.",
      "Your team's velocity looks good! Here are some tips to maintain momentum and avoid burnout.",
    ];
    const reply = responses[Math.floor(Math.random() * responses.length)];
    res.json({ success: true, message: reply, timestamp: new Date() });
  } catch (error) {
    next(error);
  }
};
